src/Entity/Stock.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Table(name: 'stock')]
#[ORM\Entity(repositoryClass: 'App\Repository\StockRepository')]
#[UniqueEntity('symbol')]
class Stock
{
    #[ORM\Column(name: 'id', type: 'integer')]
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'AUTO')]
    private int $id;

    #[ORM\Column(name: 'name', type: 'string', length: 50)]
    private string $name;

    #[ORM\Column(name: 'symbol', type: 'string', length: 20, unique: true)]
    private string $symbol;

    #[ORM\Column(name: 'currency', type: 'string', length: 3)]
    private string $currency;

    #[ORM\Column(name: 'quantity', type: 'decimal', precision: 8, scale: 2, nullable: true)]
    private ?float $quantity;

    #[ORM\Column(name: 'initialPrice', type: 'decimal', precision: 8, scale: 2, nullable: true)]
    private ?float $initialPrice;

    #[ORM\Column(name: 'currentPrice', type: 'decimal', precision: 8, scale: 2, nullable: true)]
    private ?float $currentPrice;

    #[ORM\Column(name: 'currentChange', type: 'decimal', precision: 8, scale: 2, nullable: true)]
    private ?float $currentChange;

    #[ORM\Column(name: 'createdAt', type: 'datetime')]
    private \DateTimeInterface $createdAt;

    #[ORM\Column(name: 'updatedAt', type: 'datetime', nullable: true)]
    private ?\DateTimeInterface $updatedAt;

    #[ORM\Column(name: 'displayChart', type: 'boolean')]
    private bool $displayChart = true;

    /**
     * Init the object
     */
    public function __construct()
    {
        $this->createdAt = new \DateTime();
    }

    ////////////////////////////////////////////////////////////////////////////////////////// CONVENIENCE

    /**
     * Return invested money
     * @return float|null
     */
    public function getInvestment()
    {
        if ($this->quantity && $this->initialPrice) {
            return $this->quantity * $this->initialPrice;
        } else {
            return null;
        }
    }

    /**
     * Get current value of investment
     */
    public function getCurrentValue()
    {
        if ($this->quantity && $this->initialPrice && $this->currentPrice) {
            return $this->quantity * $this->currentPrice;
        } else {
            return null;
        }
    }

    /**
     * Return profit
     * @return float
     */
    public function getProfit()
    {
        if ($this->quantity && $this->initialPrice && $this->currentPrice) {
            return $this->getCurrentValue() - $this->getInvestment();
        } else {
            return null;
        }
    }

    /**
     * Return profit percentage
     * @return float
     */
    public function getProfitPercent()
    {
        return $this->getProfit() / $this->getInvestment();
    }

    /**
     * Get percent of current change
     * @return float
     */
    public function getCurrentChangePercent()
    {
        $oldPrice = $this->currentPrice - $this->currentChange;
        if ($oldPrice) {
            return $this->currentChange / $oldPrice;
        }
        return 0;
    }

    ////////////////////////////////////////////////////////////////////////////////////////// GETTER / SETTER

    /**
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param string $name
     * @return \App\Entity\Stock
     */
    public function setName($name)
    {
        $this->name = $name;
        return $this;
    }

    /**
     * @param string $symbol
     * @return \App\Entity\Stock
     */
    public function setSymbol($symbol)
    {
        $this->symbol = $symbol;
        return $this;
    }

    /**
     * @return string
     */
    public function getSymbol()
    {
        return $this->symbol;
    }

    /**
     * @return string
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * @param string $currency
     * @return \App\Entity\Stock
     */
    public function setCurrency($currency)
    {
        $this->currency = $currency;
        return $this;
    }

    /**
     * @param float $quantity
     * @return \App\Entity\Stock
     */
    public function setQuantity($quantity)
    {
        $this->quantity = $quantity;
        return $this;
    }

    /**
     * @return float
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * @param float $initialPrice
     * @return \App\Entity\Stock
     */
    public function setInitialPrice($initialPrice)
    {
        $this->initialPrice = $initialPrice;
        return $this;
    }

    /**
     * @return float
     */
    public function getInitialPrice()
    {
        return $this->initialPrice;
    }

    /**
     * @return float
     */
    public function getCurrentPrice()
    {
        return $this->currentPrice;
    }

    /**
     * @param float $currentPrice
     * @return \App\Entity\Stock
     */
    public function setCurrentPrice($currentPrice)
    {
        $this->currentPrice = $currentPrice;
        return $this;
    }

    /**
     * @return float
     */
    public function getCurrentChange()
    {
        return $this->currentChange;
    }

    /**
     * @param float $currentChange
     * @return \App\Entity\Stock
     */
    public function setCurrentChange($currentChange)
    {
        $this->currentChange = $currentChange;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * @param \DateTime $updatedAt
     * @return \App\Entity\Stock
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTime $createdAt
     * @return \App\Entity\Stock
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
        return $this;
    }

    /**
     * @return boolean
     */
    public function isDisplayChart()
    {
        return $this->displayChart;
    }

    /**
     * @param boolean $displayChart
     *
     * @return Stock
     */
    public function setDisplayChart($displayChart)
    {
        $this->displayChart = $displayChart;
        return $this;
    }
}

src/Controller/PanelController.php
<?php

namespace App\Controller;

use App\Entity\Stock;
use App\Provider\StockPriceProvider;
use App\Repository\StockRepository;
use GuzzleHttp\Client;
use GuzzleHttp\Exception\ClientException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PanelController extends AbstractController
{
    public function __construct(
        private StockPriceProvider $stockPriceProvider,
        private StockRepository $stockRepo
    ) {
    }

    private const RANGE_INTERVAL_MAP = [
        '1d' => '2m',
        '5d' => '15m',
        '1mo' => '1h',
        '6mo' => '1d',
        'ytd' => '1wk',
        '1y' => '1wk',
        '5y' => '1mo',
        'max' => '1mo',
    ];

    /**
     * Show the stock panel
     */
    #[Route(path: '/', name: 'stock_table')]
    public function tableAction(): Response
    {
        $stocks = $this->stockPriceProvider->getStocksAndUpdate();
        return $this->render("Panel/table.html.twig", [
            'stocks' => $stocks,
        ]);
    }

    /**
     * Show the stock panel
     */
    #[Route(path: '/charts', name: 'stock_charts')]
    public function chartsAction(): Response
    {
        $stocks = $this->stockPriceProvider->getStocksAndUpdate();
        return $this->render("Panel/charts.html.twig", [
            'stocks' => $stocks,
        ]);
    }

    /**
     * Get JSON data for the chart
     */
    #[Route(path: '/charts/{id}/{range}.json', name: 'stock_charts_data')]
    public function getChartData(int $id, string $range, Request $request): Response
    {
        $stock = $this->getStock($id);
        if (!$stock) {
            throw $this->createNotFoundException('Stock not found');
        }
        if (!array_key_exists($range, self::RANGE_INTERVAL_MAP)) {
            throw $this->createNotFoundException('Invalid range');
        }

        $symbol = $stock->getSymbol();
        $interval = self::RANGE_INTERVAL_MAP[$range];

        $url = "https://query1.finance.yahoo.com/v8/finance/chart/" . $symbol . "?range=" . $range . "&includePrePost=false&interval=" . $interval;
        $client = new Client();
        try {
            $response = $client->get($url);
        } catch (ClientException $e) {
            throw $this->createNotFoundException('Client error: ' . $e->getMessage(), $e);
        }

        $json = json_decode($response->getBody(), true);
        if (!isset($json['chart']['result'][0]['timestamp'])) {
            throw $this->createNotFoundException('Timestamps not found');
        }
        if (!isset($json['chart']['result'][0]['indicators']['quote'][0]['close'])) {
            throw $this->createNotFoundException('Closing pricees not found');
        }

        $dataPrice = [];
        $dataVolume = [];
        $timestamps = $json['chart']['result'][0]['timestamp'];
        $openPrices = $json['chart']['result'][0]['indicators']['quote'][0]['open'];
        $highPrices = $json['chart']['result'][0]['indicators']['quote'][0]['high'];
        $lowPrices = $json['chart']['result'][0]['indicators']['quote'][0]['low'];
        $closingPrices = $json['chart']['result'][0]['indicators']['quote'][0]['close'];
        $volumes = $json['chart']['result'][0]['indicators']['quote'][0]['volume'];
        foreach ($timestamps as $index => $timestamp) {
            $timestampMs = $timestamp * 1000;
            $openPrice = $openPrices[$index] ?? null;
            $highPrice = $highPrices[$index] ?? null;
            $lowPrice = $lowPrices[$index] ?? null;
            $closingPrice = $closingPrices[$index] ?? null;
            $volume = $volumes[$index] ?? null;
            $dataPrice[] = [$timestampMs, $openPrice, $highPrice, $lowPrice, $closingPrice];
            $dataVolume[] = [$timestampMs, $volume];
        }

        return new JsonResponse([
            'price' => $dataPrice,
            'volume' => $dataVolume,
        ]);
    }

    /**
     * Force stock update
     */
    #[Route(path: '/update', name: 'stock_update')]
    public function updateAction(): Response
    {
        $this->stockPriceProvider->updateStocks();
        $stocks = $this->stockPriceProvider->getStocks();
        return $this->render("Panel/tableContent.html.twig", [
            'stocks' => $stocks,
        ]);
    }

    private function getStock(int $id): ?Stock
    {
        return $this->stockRepo->findOneById($id);
    }
}

templates/Panel/charts.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ parent() }} &ndash; Charts{% endblock %}

{% block body %}
<div id="stockCharts" class="container-fluid py-3">
    <ul class="nav nav-pills" id="period-tabs" role="tablist">
        <li class="nav-item"><a class="nav-link px-2 py-1 active" data-period="1d" role="tab" data-bs-toggle="tab">1d</a></li>
        <li class="nav-item"><a class="nav-link px-2 py-1" data-period="5d" role="tab" data-bs-toggle="tab">5d</a></li>
        <li class="nav-item"><a class="nav-link px-2 py-1" data-period="1mo" role="tab" data-bs-toggle="tab">1m</a></li>
        <li class="nav-item"><a class="nav-link px-2 py-1" data-period="6mo" role="tab" data-bs-toggle="tab">6m</a></li>
        <li class="nav-item"><a class="nav-link px-2 py-1" data-period="ytd" role="tab" data-bs-toggle="tab">ytd</a></li>
        <li class="nav-item"><a class="nav-link px-2 py-1" data-period="1y" role="tab" data-bs-toggle="tab">1y</a></li>
        <li class="nav-item"><a class="nav-link px-2 py-1" data-period="5y" role="tab" data-bs-toggle="tab">5y</a></li>
        <li class="nav-item"><a class="nav-link px-2 py-1" data-period="max" role="tab" data-bs-toggle="tab">max</a></li>
    </ul>

    <div class="charts row mt-2 g-2">
        {% for stock in stocks %}{% if stock.displayChart %}
            <div class="col col-md-6 col-xl-4 col-xxl-3 box-chart">
                <div class="box-inner">
                    <div class="d-flex mb-1">
                        <h3 class="flex-fill"><a href="http://finance.yahoo.com/q?s={{ stock.symbol }}" rel="external">{{ stock.name }}</a></h3>
                        {% if stock.profit is not null %}
                            <div class="profit text-end {% if stock.profit < 0 %}down{% elseif stock.profit > 0 %}up{% endif %}">
                                <div>{{ stock.profitPercent|sonata_number_format_percent({'fraction_digits': 2}, {'positive_prefix': '+'}) }}</div>
                                <div class="isPrivate">{{ stock.profit|sonata_number_format_currency(stock.currency, {}, {'positive_prefix': '+'}) }}</div>
                            </div>
                        {% endif %}
                        {% if stock.currentChange is not null %}
                            <div class="profit text-end {% if stock.currentChange < 0 %}down{% elseif stock.currentChange > 0 %}up{% endif %}">
                                <div><span class="indicator"></span>{{ stock.currentChangePercent|sonata_number_format_percent({'fraction_digits': 2}, {'positive_prefix': '+'}) }}</div>
                                <div class="isPrivate">{{ stock.currentChange|sonata_number_format_currency(stock.currency, {}, {'positive_prefix': '+'}) }}</div>
                            </div>
                        {% endif %}
                    </div>
                    <div class="chart" id="chart-{{ stock.id }}" data-stock-id="{{ stock.id }}"></div>
                </div>
            </div>
        {% endif %}{% endfor %}
    </div>

</div>
{% endblock %}

templates/Panel/table.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ parent() }} &ndash; Tabellen{% endblock %}

{% block body %}
    <div id="stockTable" class="container-lg py-3">
        {% include "Panel/tableContent.html.twig" %}
    </div>
{% endblock %}

templates/Panel/tableContent.html.twig
<table class="stocks table table-striped">
    <colgroup>
        <col style="width:50%;">
        <col style="width:10%;" class="hideColumn isPrivate">
        <col style="width:10%;" class="hideColumn">
        <col style="width:10%;" class="hideColumn">
        <col style="width:10%;">
        <col style="width:10%;">
    </colgroup>
    <thead>
    <tr>
        <th>Aktie</th>
        <th class="d-none d-sm-table-cell isPrivate">Anzahl</th>
        <th class="d-none d-sm-table-cell">Kauf</th>
        <th class="d-none d-sm-table-cell">Aktuell</th>
        <th>Profit</th>
        <th>Heute</th>
    </tr>
    </thead>
    <tbody>
    {% for stock in stocks %}
        <tr>
            <th>
                <div>
                    <a href="http://finance.yahoo.com/q?s={{ stock.symbol }}" rel="external">{{ stock.name }}</a>
                    <span class="actions">
                        <a href="{{ path("stock_edit", {"id": stock.id}) }}" class="btn btn-primary px-1 py-0"><span class="bi bi-pencil-fill"></span></a>
                        <button class="btn btn-danger px-1 py-0" data-delete-stock="{{ stock.id }}"><span class="bi bi-x-circle-fill"></span></button>
                    </span>
                </div>
            </th>

            <td class="d-none d-sm-table-cell isPrivate">{% if stock.quantity %}{{ stock.quantity }}{% else %}&ndash;{% endif %}</td>

            <td class="d-none d-sm-table-cell">
                {% if stock.initialPrice is not null %}
                    <div>{{ stock.initialPrice|sonata_number_format_currency(stock.currency) }}</div>
                    {% if stock.investment %}<div class="isPrivate">{{ stock.investment|sonata_number_format_currency(stock.currency) }}</div>{% endif %}
                {% else %}
                    &ndash;
                {% endif %}
            </td>

            <td class="d-none d-sm-table-cell">
                {% if stock.currentPrice is not null %}
                    <div>{{ stock.currentPrice|sonata_number_format_currency(stock.currency) }}</div>
                    {% if stock.currentValue %}<div class="isPrivate">{{ stock.currentValue|sonata_number_format_currency(stock.currency) }}</div>{% endif %}
                {% else %}
                    &ndash;
                {% endif %}
            </td>

            {% if stock.profit is not null %}
                <td class="{% if stock.profit < 0 %}down{% elseif stock.profit > 0 %}up{% endif %}">
                    <div>{{ stock.profitPercent|sonata_number_format_percent({'fraction_digits': 2}, {'positive_prefix': '+'}) }}</div>
                    <div class="isPrivate">{{ stock.profit|sonata_number_format_currency(stock.currency, {}, {'positive_prefix': '+'}) }}</div>
                </td>
            {% else %}
                <td>&ndash;</td>
            {% endif %}

            {% if stock.currentChange is not null %}
                <td class="{% if stock.currentChange < 0 %}down{% elseif stock.currentChange > 0 %}up{% endif %}">
                    <div><span class="indicator"></span>{{ stock.currentChangePercent|sonata_number_format_percent({'fraction_digits': 2}, {'positive_prefix': '+'}) }}</div>
                    <div class="isPrivate">{{ stock.currentChange|sonata_number_format_currency(stock.currency, {}, {'positive_prefix': '+'}) }}</div>
                </td>
            {% else %}
                <td>&ndash;</td>
            {% endif %}
        </tr>
    {% endfor %}
    </tbody>
{#    <tfoot>#}
{#        <tr>#}
{#            <td></td>#}
{#            <td class="d-none d-sm-table-cell isPrivate"></td>#}
{#            <td class="d-none d-sm-table-cell"><div class="isPrivate">61.000,00 $</div></td>#}
{#            <td class="d-none d-sm-table-cell"><div class="isPrivate">1.586.250,00 $</div></td>#}
{#            <td class="up">#}
{#                <div>+2.377,08 %</div>#}
{#                <div class="isPrivate">+1.426.250,00 $</div>#}
{#            </td>#}
{#            <td class="up">#}
{#                <div><span class="indicator"></span>+0,22&nbsp;%</div>#}
{#                <div class="isPrivate">+0,39&nbsp;$</div>#}
{#            </td>#}
{#        </tr>#}
{#    </tfoot>#}
</table>